// Generated by rstantools.  Do not edit by hand.

/*
    BayesianEFA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BayesianEFA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BayesianEFA.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_befa_null_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 60> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 39, column 2 to column 37)",
  " (in 'string', line 40, column 2 to column 27)",
  " (in 'string', line 43, column 2 to column 51)",
  " (in 'string', line 48, column 4 to column 51)",
  " (in 'string', line 47, column 23 to line 49, column 3)",
  " (in 'string', line 47, column 2 to line 49, column 3)",
  " (in 'string', line 50, column 2 to column 74)",
  " (in 'string', line 51, column 2 to column 76)",
  " (in 'string', line 57, column 6 to column 60)",
  " (in 'string', line 56, column 11 to line 58, column 5)",
  " (in 'string', line 55, column 6 to column 74)",
  " (in 'string', line 54, column 25 to line 56, column 5)",
  " (in 'string', line 54, column 4 to line 58, column 5)",
  " (in 'string', line 53, column 22 to line 59, column 3)",
  " (in 'string', line 53, column 2 to line 59, column 3)",
  " (in 'string', line 64, column 6 to column 24)",
  " (in 'string', line 66, column 8 to column 30)",
  " (in 'string', line 70, column 10 to column 60)",
  " (in 'string', line 69, column 15 to line 71, column 9)",
  " (in 'string', line 68, column 10 to column 64)",
  " (in 'string', line 67, column 29 to line 69, column 9)",
  " (in 'string', line 67, column 8 to line 71, column 9)",
  " (in 'string', line 65, column 22 to line 72, column 7)",
  " (in 'string', line 65, column 6 to line 72, column 7)",
  " (in 'string', line 63, column 30 to line 73, column 5)",
  " (in 'string', line 63, column 4 to line 73, column 5)",
  " (in 'string', line 62, column 24 to line 74, column 3)",
  " (in 'string', line 62, column 2 to line 74, column 3)",
  " (in 'string', line 21, column 2 to column 26)",
  " (in 'string', line 22, column 2 to column 28)",
  " (in 'string', line 23, column 2 to column 17)",
  " (in 'string', line 25, column 2 to column 35)",
  " (in 'string', line 27, column 9 to column 10)",
  " (in 'string', line 27, column 2 to column 18)",
  " (in 'string', line 28, column 13 to column 14)",
  " (in 'string', line 28, column 2 to column 22)",
  " (in 'string', line 30, column 9 to column 21)",
  " (in 'string', line 30, column 23 to column 24)",
  " (in 'string', line 30, column 2 to column 33)",
  " (in 'string', line 31, column 2 to column 23)",
  " (in 'string', line 32, column 8 to column 20)",
  " (in 'string', line 32, column 2 to column 41)",
  " (in 'string', line 33, column 8 to column 20)",
  " (in 'string', line 33, column 22 to column 29)",
  " (in 'string', line 33, column 2 to column 61)",
  " (in 'string', line 35, column 2 to column 27)",
  " (in 'string', line 36, column 2 to column 30)",
  " (in 'string', line 39, column 9 to column 32)",
  " (in 'string', line 40, column 18 to column 19)",
  " (in 'string', line 43, column 13 to column 14)",
  " (in 'string', line 9, column 11 to column 12)",
  " (in 'string', line 9, column 4 to column 32)",
  " (in 'string', line 10, column 4 to column 41)",
  " (in 'string', line 11, column 4 to column 58)",
  " (in 'string', line 12, column 4 to column 70)",
  " (in 'string', line 13, column 4 to column 53)",
  " (in 'string', line 8, column 53 to line 14, column 3)",
  " (in 'string', line 17, column 4 to column 84)",
  " (in 'string', line 16, column 56 to line 18, column 3)"};
template <typename T2__, typename T3__, typename T4__, typename T5__,
          stan::require_all_t<stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_eigen_matrix_dynamic<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_eigen_matrix_dynamic<T5__>,
                              stan::is_vt_not_complex<T5__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T2__>, stan::base_type_t<T3__>,
  stan::base_type_t<T4__>, stan::base_type_t<T5__>>
sufficient_ll_raw(const int& N, const int& J, const T2__& m_obs_arg__,
                  const T3__& nu_arg__, const T4__& S_obs_arg__, const T5__&
                  Sigma_arg__, std::ostream* pstream__);
template <typename T1__, typename T2__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>, stan::base_type_t<T2__>>
sufficient_ll_cov(const int& N, const T1__& S_arg__, const T2__& Sigma_arg__,
                  std::ostream* pstream__);
template <typename T2__, typename T3__, typename T4__, typename T5__,
          stan::require_all_t<stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_eigen_matrix_dynamic<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::is_eigen_matrix_dynamic<T5__>,
                              stan::is_vt_not_complex<T5__>>*>
stan::promote_args_t<stan::base_type_t<T2__>, stan::base_type_t<T3__>,
  stan::base_type_t<T4__>, stan::base_type_t<T5__>>
sufficient_ll_raw(const int& N, const int& J, const T2__& m_obs_arg__,
                  const T3__& nu_arg__, const T4__& S_obs_arg__, const T5__&
                  Sigma_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>,
                             stan::base_type_t<T5__>>;
  int current_statement__ = 0;
  const auto& m_obs = stan::math::to_ref(m_obs_arg__);
  const auto& nu = stan::math::to_ref(nu_arg__);
  const auto& S_obs = stan::math::to_ref(S_obs_arg__);
  const auto& Sigma = stan::math::to_ref(Sigma_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 51;
    stan::math::validate_non_negative_index("diff", "J", J);
    Eigen::Matrix<local_scalar_t__,-1,1> diff =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
    current_statement__ = 52;
    stan::model::assign(diff, stan::math::subtract(m_obs, nu),
      "assigning variable diff");
    local_scalar_t__ logdet = DUMMY_VAR__;
    current_statement__ = 53;
    logdet = stan::math::log_determinant(Sigma);
    local_scalar_t__ tr_part = DUMMY_VAR__;
    current_statement__ = 54;
    tr_part = stan::math::trace(stan::math::mdivide_right_spd(S_obs, Sigma));
    local_scalar_t__ mean_quad = DUMMY_VAR__;
    current_statement__ = 55;
    mean_quad = stan::math::dot_product(diff,
                  stan::math::mdivide_left_spd(Sigma, diff));
    current_statement__ = 56;
    return ((-0.5 * N) * ((logdet + tr_part) + mean_quad));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T1__, typename T2__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::promote_args_t<stan::base_type_t<T1__>, stan::base_type_t<T2__>>
sufficient_ll_cov(const int& N, const T1__& S_arg__, const T2__& Sigma_arg__,
                  std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  const auto& S = stan::math::to_ref(S_arg__);
  const auto& Sigma = stan::math::to_ref(Sigma_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 58;
    return ((-0.5 * N) * (stan::math::log_determinant(Sigma) +
           stan::math::trace(stan::math::mdivide_right_spd(S, Sigma))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_befa_null final : public model_base_crtp<model_befa_null> {
private:
  int N_complete;
  int N_incomplete;
  int J;
  int model_type;
  Eigen::Matrix<double,-1,1> m_obs_data__;
  Eigen::Matrix<double,-1,-1> S_obs_data__;
  Eigen::Matrix<double,-1,-1> Y_miss_data__;
  int max_obs;
  std::vector<int> n_obs;
  std::vector<std::vector<int>> obs_idx;
  Eigen::Matrix<double,-1,1> pr_nu_data__;
  Eigen::Matrix<double,-1,1> pr_sigma_data__;
  int nu_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> m_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> S_obs{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_miss{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> pr_nu{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> pr_sigma{nullptr, 0};
public:
  ~model_befa_null() {}
  model_befa_null(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_befa_null_namespace::model_befa_null";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 29;
      context__.validate_dims("data initialization", "N_complete", "int",
        std::vector<size_t>{});
      N_complete = std::numeric_limits<int>::min();
      current_statement__ = 29;
      N_complete = context__.vals_i("N_complete")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "N_complete",
        N_complete, 0);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "N_incomplete", "int",
        std::vector<size_t>{});
      N_incomplete = std::numeric_limits<int>::min();
      current_statement__ = 30;
      N_incomplete = context__.vals_i("N_incomplete")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "N_incomplete",
        N_incomplete, 0);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 31;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "model_type", "int",
        std::vector<size_t>{});
      model_type = std::numeric_limits<int>::min();
      current_statement__ = 32;
      model_type = context__.vals_i("model_type")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "model_type",
        model_type, 1);
      current_statement__ = 32;
      stan::math::check_less_or_equal(function__, "model_type", model_type, 2);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("m_obs", "J", J);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "m_obs", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      m_obs_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                       std::numeric_limits<double>::quiet_NaN());
      new (&m_obs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(m_obs_data__.data(), J);
      {
        std::vector<local_scalar_t__> m_obs_flat__;
        current_statement__ = 34;
        m_obs_flat__ = context__.vals_r("m_obs");
        current_statement__ = 34;
        pos__ = 1;
        current_statement__ = 34;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 34;
          stan::model::assign(m_obs, m_obs_flat__[(pos__ - 1)],
            "assigning variable m_obs", stan::model::index_uni(sym1__));
          current_statement__ = 34;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 35;
      stan::math::validate_non_negative_index("S_obs", "J", J);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("S_obs", "J", J);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "S_obs", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(J)});
      S_obs_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                       std::numeric_limits<double>::quiet_NaN());
      new (&S_obs)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(S_obs_data__.data(), J, J);
      {
        std::vector<local_scalar_t__> S_obs_flat__;
        current_statement__ = 36;
        S_obs_flat__ = context__.vals_r("S_obs");
        current_statement__ = 36;
        pos__ = 1;
        current_statement__ = 36;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 36;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 36;
            stan::model::assign(S_obs, S_obs_flat__[(pos__ - 1)],
              "assigning variable S_obs", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 36;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 36;
      stan::math::check_cov_matrix(function__, "S_obs", S_obs);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("Y_miss", "N_incomplete",
        N_incomplete);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("Y_miss", "J", J);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "Y_miss", "double",
        std::vector<size_t>{static_cast<size_t>(N_incomplete),
          static_cast<size_t>(J)});
      Y_miss_data__ = Eigen::Matrix<double,-1,-1>::Constant(N_incomplete, J,
                        std::numeric_limits<double>::quiet_NaN());
      new (&Y_miss)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_miss_data__.data(),
        N_incomplete, J);
      {
        std::vector<local_scalar_t__> Y_miss_flat__;
        current_statement__ = 39;
        Y_miss_flat__ = context__.vals_r("Y_miss");
        current_statement__ = 39;
        pos__ = 1;
        current_statement__ = 39;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 39;
          for (int sym2__ = 1; sym2__ <= N_incomplete; ++sym2__) {
            current_statement__ = 39;
            stan::model::assign(Y_miss, Y_miss_flat__[(pos__ - 1)],
              "assigning variable Y_miss", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 39;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 40;
      context__.validate_dims("data initialization", "max_obs", "int",
        std::vector<size_t>{});
      max_obs = std::numeric_limits<int>::min();
      current_statement__ = 40;
      max_obs = context__.vals_i("max_obs")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "max_obs", max_obs, 0);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("n_obs", "N_incomplete",
        N_incomplete);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{static_cast<size_t>(N_incomplete)});
      n_obs = std::vector<int>(N_incomplete, std::numeric_limits<int>::min());
      current_statement__ = 42;
      n_obs = context__.vals_i("n_obs");
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 0);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("obs_idx", "N_incomplete",
        N_incomplete);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("obs_idx", "max_obs", max_obs);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "obs_idx", "int",
        std::vector<size_t>{static_cast<size_t>(N_incomplete),
          static_cast<size_t>(max_obs)});
      obs_idx = std::vector<std::vector<int>>(N_incomplete,
                  std::vector<int>(max_obs, std::numeric_limits<int>::min()));
      {
        std::vector<int> obs_idx_flat__;
        current_statement__ = 45;
        obs_idx_flat__ = context__.vals_i("obs_idx");
        current_statement__ = 45;
        pos__ = 1;
        current_statement__ = 45;
        for (int sym1__ = 1; sym1__ <= max_obs; ++sym1__) {
          current_statement__ = 45;
          for (int sym2__ = 1; sym2__ <= N_incomplete; ++sym2__) {
            current_statement__ = 45;
            stan::model::assign(obs_idx, obs_idx_flat__[(pos__ - 1)],
              "assigning variable obs_idx", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 45;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "obs_idx", obs_idx, 0);
      current_statement__ = 45;
      stan::math::check_less_or_equal(function__, "obs_idx", obs_idx, J);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "pr_nu", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      pr_nu_data__ = Eigen::Matrix<double,-1,1>::Constant(2,
                       std::numeric_limits<double>::quiet_NaN());
      new (&pr_nu)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(pr_nu_data__.data(), 2);
      {
        std::vector<local_scalar_t__> pr_nu_flat__;
        current_statement__ = 46;
        pr_nu_flat__ = context__.vals_r("pr_nu");
        current_statement__ = 46;
        pos__ = 1;
        current_statement__ = 46;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 46;
          stan::model::assign(pr_nu, pr_nu_flat__[(pos__ - 1)],
            "assigning variable pr_nu", stan::model::index_uni(sym1__));
          current_statement__ = 46;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "pr_nu", pr_nu, 0);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "pr_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(3)});
      pr_sigma_data__ = Eigen::Matrix<double,-1,1>::Constant(3,
                          std::numeric_limits<double>::quiet_NaN());
      new (&pr_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(pr_sigma_data__.data(), 3);
      {
        std::vector<local_scalar_t__> pr_sigma_flat__;
        current_statement__ = 47;
        pr_sigma_flat__ = context__.vals_r("pr_sigma");
        current_statement__ = 47;
        pos__ = 1;
        current_statement__ = 47;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          current_statement__ = 47;
          stan::model::assign(pr_sigma, pr_sigma_flat__[(pos__ - 1)],
            "assigning variable pr_sigma", stan::model::index_uni(sym1__));
          current_statement__ = 47;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "pr_sigma", pr_sigma, 0);
      current_statement__ = 48;
      nu_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 48;
      nu_1dim__ = (stan::math::logical_eq(model_type, 1) ? J : 0);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("nu",
        "model_type == 1 ? J : 0", nu_1dim__);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("sigma", "J", J);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("Sigma", "J", J);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("Sigma", "J", J);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = nu_1dim__ + J;
  }
  inline std::string model_name() const final {
    return "model_befa_null";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_befa_null_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nu_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      nu = in__.template read<
             Eigen::Matrix<local_scalar_t__,-1,1>>(nu_1dim__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, J);
      Eigen::Matrix<local_scalar_t__,-1,-1> Sigma =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, J, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(Sigma,
        stan::math::diag_matrix(stan::math::square(sigma)),
        "assigning variable Sigma");
      current_statement__ = 3;
      stan::math::check_cov_matrix(function__, "Sigma", Sigma);
      {
        current_statement__ = 6;
        if (stan::math::logical_eq(model_type, 1)) {
          current_statement__ = 4;
          lp_accum__.add(stan::math::normal_lpdf<false>(nu,
                           stan::model::rvalue(pr_nu, "pr_nu",
                             stan::model::index_uni(1)),
                           stan::model::rvalue(pr_nu, "pr_nu",
                             stan::model::index_uni(2))));
        }
        current_statement__ = 7;
        lp_accum__.add(stan::math::student_t_lpdf<false>(sigma,
                         stan::model::rvalue(pr_sigma, "pr_sigma",
                           stan::model::index_uni(1)),
                         stan::model::rvalue(pr_sigma, "pr_sigma",
                           stan::model::index_uni(2)),
                         stan::model::rvalue(pr_sigma, "pr_sigma",
                           stan::model::index_uni(3))));
        current_statement__ = 8;
        lp_accum__.add((J *
          -stan::math::student_t_lccdf(0,
             stan::model::rvalue(pr_sigma, "pr_sigma",
               stan::model::index_uni(1)),
             stan::model::rvalue(pr_sigma, "pr_sigma",
               stan::model::index_uni(2)),
             stan::model::rvalue(pr_sigma, "pr_sigma",
               stan::model::index_uni(3)))));
        current_statement__ = 15;
        if (stan::math::logical_gt(N_complete, 0)) {
          current_statement__ = 13;
          if (stan::math::logical_eq(model_type, 1)) {
            current_statement__ = 11;
            lp_accum__.add(sufficient_ll_raw(N_complete, J, m_obs, nu, S_obs,
                             Sigma, pstream__));
          } else {
            current_statement__ = 9;
            lp_accum__.add(sufficient_ll_cov(N_complete, S_obs, Sigma,
                             pstream__));
          }
        }
        current_statement__ = 28;
        if (stan::math::logical_gt(N_incomplete, 0)) {
          current_statement__ = 26;
          for (int i = 1; i <= N_incomplete; ++i) {
            int ni = std::numeric_limits<int>::min();
            current_statement__ = 16;
            ni = stan::model::rvalue(n_obs, "n_obs",
                   stan::model::index_uni(i));
            current_statement__ = 24;
            for (int k = 1; k <= ni; ++k) {
              int j = std::numeric_limits<int>::min();
              current_statement__ = 17;
              j = stan::model::rvalue(obs_idx, "obs_idx",
                    stan::model::index_uni(i), stan::model::index_uni(k));
              current_statement__ = 22;
              if (stan::math::logical_eq(model_type, 1)) {
                current_statement__ = 20;
                lp_accum__.add(stan::math::normal_lpdf<false>(
                                 stan::model::rvalue(Y_miss, "Y_miss",
                                   stan::model::index_uni(i),
                                   stan::model::index_uni(j)),
                                 stan::model::rvalue(nu, "nu",
                                   stan::model::index_uni(j)),
                                 stan::model::rvalue(sigma, "sigma",
                                   stan::model::index_uni(j))));
              } else {
                current_statement__ = 18;
                lp_accum__.add(stan::math::normal_lpdf<false>(
                                 stan::model::rvalue(Y_miss, "Y_miss",
                                   stan::model::index_uni(i),
                                   stan::model::index_uni(j)), 0,
                                 stan::model::rvalue(sigma, "sigma",
                                   stan::model::index_uni(j))));
              }
            }
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_befa_null_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> nu =
        Eigen::Matrix<double,-1,1>::Constant(nu_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      nu = in__.template read<
             Eigen::Matrix<local_scalar_t__,-1,1>>(nu_1dim__);
      Eigen::Matrix<double,-1,1> sigma =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, J);
      Eigen::Matrix<double,-1,-1> Sigma =
        Eigen::Matrix<double,-1,-1>::Constant(J, J,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(nu);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      stan::model::assign(Sigma,
        stan::math::diag_matrix(stan::math::square(sigma)),
        "assigning variable Sigma");
      current_statement__ = 3;
      stan::math::check_cov_matrix(function__, "Sigma", Sigma);
      if (emit_transformed_parameters__) {
        out__.write(Sigma);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nu_1dim__,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(nu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nu_1dim__),
        "assigning variable nu");
      out__.write(nu);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(sigma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable sigma");
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "nu", "double",
        std::vector<size_t>{static_cast<size_t>(nu_1dim__)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nu_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> nu_flat__;
        current_statement__ = 1;
        nu_flat__ = context__.vals_r("nu");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= nu_1dim__; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(nu, nu_flat__[(pos__ - 1)],
            "assigning variable nu", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(nu);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_flat__;
        current_statement__ = 2;
        sigma_flat__ = context__.vals_r("sigma");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(sigma, sigma_flat__[(pos__ - 1)],
            "assigning variable sigma", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"nu", "sigma"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"Sigma"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    nu_1dim__)},
                std::vector<size_t>{static_cast<size_t>(J)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J),
               static_cast<size_t>(J)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nu_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          param_names__.emplace_back(std::string() + "Sigma" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nu_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= (J + ((J * (J - 1)) / 2)); ++sym1__) {
        param_names__.emplace_back(std::string() + "Sigma" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nu_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"Sigma\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nu_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"Sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((J + ((J * (J - 1)) /2))) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (nu_1dim__ + J);
    const size_t num_transformed = emit_transformed_parameters * ((J * J));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (nu_1dim__ + J);
    const size_t num_transformed = emit_transformed_parameters * ((J * J));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_befa_null_namespace::model_befa_null;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_befa_null_namespace::profiles__;
}
#endif
#endif
